# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tribarb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tribarb
  pod 'Stripe'
  pod 'SwiftyJSON', '5.0.0'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'Cosmos'
  pod 'TinyConstraints'
  pod 'PushNotifications'
  pod 'Floaty', '~> 4.2.0'
  pod 'SkeletonView'

#  target 'tribarbTests' do
 #   inherit! :search_paths
    # Pods for testing
 # end

  #target 'tribarbUITests' do
    # Pods for testing
  #end

end
